// Code generated by protoc-gen-grain. DO NOT EDIT.

package grainactor

import (
	cluster "github.com/asynkron/protoactor-go/service/cluster"
)

var (
	allServiceGrainClients = &allServiceGrainClientSet{}
)

type allServiceGrainClientSet struct {
	baseCrossMailGrainClient *BaseCrossMailGrainClient
	baseCrossSnsGrainClient  *BaseCrossSnsGrainClient
}

// InitServiceGrainClients initializes shared base grain clients for all generated grain services.
func InitServiceGrainClients(fn func() *cluster.Cluster, opts ...cluster.GrainCallOption) {
	allServiceGrainClients.baseCrossMailGrainClient = NewBaseCrossMailGrainClient(fn, opts...)
	allServiceGrainClients.baseCrossSnsGrainClient = NewBaseCrossSnsGrainClient(fn, opts...)
}

// GetBaseCrossMailGrainClient returns the shared base client for CrossMail.
func GetBaseCrossMailGrainClient() *BaseCrossMailGrainClient {
	return allServiceGrainClients.baseCrossMailGrainClient
}

// GetBaseCrossSnsGrainClient returns the shared base client for CrossSns.
func GetBaseCrossSnsGrainClient() *BaseCrossSnsGrainClient {
	return allServiceGrainClients.baseCrossSnsGrainClient
}
