// Code generated by protoc-gen-grain. DO NOT EDIT.
// versions:
//  protoc-gen-grain v0.7.0
//  protoc           v7.34.1
// source: test/grainactor/grainactor.proto

package grainactor

import (
	context "context"
	fmt "fmt"
	actor "github.com/asynkron/protoactor-go/actor"
	cluster "github.com/asynkron/protoactor-go/service/cluster"
	grainactor "github.com/asynkron/protoactor-go/service/grainactor"
	proto "google.golang.org/protobuf/proto"
	slog "log/slog"
)

const ActorKindNameCrossSns = "player_equip"
const ActorNodeTypeCrossSns = "game"
const ActorGroupNameCrossSns = "player"

var xCrossSnsFactory func() CrossSns

// CrossSnsFactory produces a CrossSns
func CrossSnsFactory(factory func() CrossSns) {
	xCrossSnsFactory = factory
}

// GetCrossSnsGrainClient instantiates a new CrossSnsGrainClient with given Identity
func GetCrossSnsGrainClient(c *cluster.Cluster, id string) *CrossSnsGrainClient {
	if c == nil {
		panic(fmt.Errorf("nil cluster instance"))
	}
	if id == "" {
		panic(fmt.Errorf("empty id"))
	}
	return &CrossSnsGrainClient{Identity: id, cluster: c}
}

// GetCrossSnsKind instantiates a new cluster.Kind for CrossSns

// GetCrossSnsKind instantiates a new cluster.Kind for CrossSns

// CrossSns interfaces the services available to the CrossSns
type CrossSns interface {
	RoleSimple(ctx context.Context, req *RoleSimpleRequest) (*RoleSimpleResponse, error)

	Keepalive(ctx context.Context, req *KeepaliveRequest) (*KeepaliveResponse, error)
}

// CrossSnsGrainClient holds the base data for the CrossSnsGrain
type CrossSnsGrainClient struct {
	Identity string
	cluster  *cluster.Cluster
}

// RoleSimple requests the execution on to the cluster with CallOptions
func (g *CrossSnsGrainClient) RoleSimple(identity string, r *RoleSimpleRequest, opts ...cluster.GrainCallOption) (*RoleSimpleResponse, error) {
	var placementContext *cluster.PlacementContext
	placementContext = &cluster.PlacementContext{NodeType: "game"}
	return g.RoleSimpleWithPlacement(placementContext, identity, r, opts...)
}

func (g *CrossSnsGrainClient) RoleSimpleByRouteKey(identity string, routeKey uint64, r *RoleSimpleRequest, opts ...cluster.GrainCallOption) (*RoleSimpleResponse, error) {
	return g.RoleSimpleWithPlacement(&cluster.PlacementContext{NodeType: "game", RouteKey: routeKey}, identity, r, opts...)
}

func (g *CrossSnsGrainClient) RoleSimpleWithPlacement(placementContext *cluster.PlacementContext, identity string, r *RoleSimpleRequest, opts ...cluster.GrainCallOption) (*RoleSimpleResponse, error) {
	if g.cluster.Config.RequestLog {
		g.cluster.Logger().Info("Requesting", slog.String("identity", g.Identity), slog.String("kind", "CrossSns"), slog.String("method", "RoleSimple"), slog.Any("request", r))
	}
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 0, MessageData: bytes}
	resp, err := g.cluster.Request(placementContext, identity, ActorKindNameCrossSns, reqMsg, opts...)
	if err != nil {
		return nil, fmt.Errorf("error request: %w", err)
	}
	switch msg := resp.(type) {
	case *RoleSimpleResponse:
		return msg, nil
	case *cluster.GrainErrorResponse:
		if msg == nil {
			return nil, nil
		}
		return nil, msg
	default:
		return nil, fmt.Errorf("unknown response type %T", resp)
	}
}

// Keepalive requests the execution on to the cluster with CallOptions
func (g *CrossSnsGrainClient) Keepalive(identity string, r *KeepaliveRequest, opts ...cluster.GrainCallOption) (*KeepaliveResponse, error) {
	var placementContext *cluster.PlacementContext
	placementContext = &cluster.PlacementContext{NodeType: "game"}
	return g.KeepaliveWithPlacement(placementContext, identity, r, opts...)
}

func (g *CrossSnsGrainClient) KeepaliveByRouteKey(identity string, routeKey uint64, r *KeepaliveRequest, opts ...cluster.GrainCallOption) (*KeepaliveResponse, error) {
	return g.KeepaliveWithPlacement(&cluster.PlacementContext{NodeType: "game", RouteKey: routeKey}, identity, r, opts...)
}

func (g *CrossSnsGrainClient) KeepaliveWithPlacement(placementContext *cluster.PlacementContext, identity string, r *KeepaliveRequest, opts ...cluster.GrainCallOption) (*KeepaliveResponse, error) {
	if g.cluster.Config.RequestLog {
		g.cluster.Logger().Info("Requesting", slog.String("identity", g.Identity), slog.String("kind", "CrossSns"), slog.String("method", "Keepalive"), slog.Any("request", r))
	}
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 1, MessageData: bytes}
	resp, err := g.cluster.Request(placementContext, identity, ActorKindNameCrossSns, reqMsg, opts...)
	if err != nil {
		return nil, fmt.Errorf("error request: %w", err)
	}
	switch msg := resp.(type) {
	case *KeepaliveResponse:
		return msg, nil
	case *cluster.GrainErrorResponse:
		if msg == nil {
			return nil, nil
		}
		return nil, msg
	default:
		return nil, fmt.Errorf("unknown response type %T", resp)
	}
}

const ActorKindNameCrossMail = "player_equip"
const ActorNodeTypeCrossMail = "game"
const ActorGroupNameCrossMail = "player"

var xCrossMailFactory func() CrossMail

// CrossMailFactory produces a CrossMail
func CrossMailFactory(factory func() CrossMail) {
	xCrossMailFactory = factory
}

// GetCrossMailGrainClient instantiates a new CrossMailGrainClient with given Identity
func GetCrossMailGrainClient(c *cluster.Cluster, id string) *CrossMailGrainClient {
	if c == nil {
		panic(fmt.Errorf("nil cluster instance"))
	}
	if id == "" {
		panic(fmt.Errorf("empty id"))
	}
	return &CrossMailGrainClient{Identity: id, cluster: c}
}

// GetCrossMailKind instantiates a new cluster.Kind for CrossMail

// GetCrossMailKind instantiates a new cluster.Kind for CrossMail

// CrossMail interfaces the services available to the CrossMail
type CrossMail interface {
	LoadMail(ctx context.Context, req *LoadMailRequest) (*LoadMailResponse, error)
}

// CrossMailGrainClient holds the base data for the CrossMailGrain
type CrossMailGrainClient struct {
	Identity string
	cluster  *cluster.Cluster
}

// LoadMail requests the execution on to the cluster with CallOptions
func (g *CrossMailGrainClient) LoadMail(identity string, r *LoadMailRequest, opts ...cluster.GrainCallOption) (*LoadMailResponse, error) {
	var placementContext *cluster.PlacementContext
	placementContext = &cluster.PlacementContext{NodeType: "game"}
	return g.LoadMailWithPlacement(placementContext, identity, r, opts...)
}

func (g *CrossMailGrainClient) LoadMailByRouteKey(identity string, routeKey uint64, r *LoadMailRequest, opts ...cluster.GrainCallOption) (*LoadMailResponse, error) {
	return g.LoadMailWithPlacement(&cluster.PlacementContext{NodeType: "game", RouteKey: routeKey}, identity, r, opts...)
}

func (g *CrossMailGrainClient) LoadMailWithPlacement(placementContext *cluster.PlacementContext, identity string, r *LoadMailRequest, opts ...cluster.GrainCallOption) (*LoadMailResponse, error) {
	if g.cluster.Config.RequestLog {
		g.cluster.Logger().Info("Requesting", slog.String("identity", g.Identity), slog.String("kind", "CrossMail"), slog.String("method", "LoadMail"), slog.Any("request", r))
	}
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 2, MessageData: bytes}
	resp, err := g.cluster.Request(placementContext, identity, ActorKindNameCrossMail, reqMsg, opts...)
	if err != nil {
		return nil, fmt.Errorf("error request: %w", err)
	}
	switch msg := resp.(type) {
	case *LoadMailResponse:
		return msg, nil
	case *cluster.GrainErrorResponse:
		if msg == nil {
			return nil, nil
		}
		return nil, msg
	default:
		return nil, fmt.Errorf("unknown response type %T", resp)
	}
}

type PlayerActor interface {
	CrossSns
	CrossMail
}

type playerHandler struct {
	handler PlayerActor
}

func (h *playerHandler) Receive(ctx grainactor.Context, req *cluster.GrainRequest) (proto.Message, error) {
	switch req.MethodIndex {
	case 0:
		msg := &RoleSimpleRequest{}
		if err := proto.Unmarshal(req.MessageData, msg); err != nil {
			return nil, cluster.NewGrainErrorResponse(cluster.ErrorReason_INVALID_ARGUMENT, err.Error()).
				WithMetadata(map[string]string{
					"argument": msg.String(),
				})
		}
		return h.handler.RoleSimple(ctx, msg)
	case 1:
		msg := &KeepaliveRequest{}
		if err := proto.Unmarshal(req.MessageData, msg); err != nil {
			return nil, cluster.NewGrainErrorResponse(cluster.ErrorReason_INVALID_ARGUMENT, err.Error()).
				WithMetadata(map[string]string{
					"argument": msg.String(),
				})
		}
		return h.handler.Keepalive(ctx, msg)
	case 2:
		msg := &LoadMailRequest{}
		if err := proto.Unmarshal(req.MessageData, msg); err != nil {
			return nil, cluster.NewGrainErrorResponse(cluster.ErrorReason_INVALID_ARGUMENT, err.Error()).
				WithMetadata(map[string]string{
					"argument": msg.String(),
				})
		}
		return h.handler.LoadMail(ctx, msg)
	default:
		return nil, cluster.NewGrainErrorResponse(cluster.ErrorReason_NOT_FOUND, fmt.Sprintf("unknown grain method index %d", req.MethodIndex))
	}
}

func NewPlayerBaseActor(handler PlayerActor, state any, opts ...grainactor.Option) actor.Actor {
	if state != nil {
		opts = append(opts, grainactor.WithState(state))
	}
	return grainactor.NewBaseActor("player", "player_equip", &playerHandler{handler: handler}, opts...)
}

func NewPlayerKind(handler PlayerActor, state any, opts ...actor.PropsOption) *cluster.Kind {
	props := actor.PropsFromProducer(func() actor.Actor {
		return NewPlayerBaseActor(handler, state)
	}, opts...)
	return cluster.NewKind("player_equip", props)
}

func respond[T proto.Message](ctx cluster.GrainContext) func(T) {
	return func(resp T) {
		ctx.Respond(resp)
	}
}
