// Code generated by protoc-gen-grain. DO NOT EDIT.
// versions:
//  protoc-gen-grain v0.7.0
//  protoc           v7.34.1
// source: test/grainactor/grainactor.proto

package grainactor

import (
	context "context"
	fmt "fmt"
	actor "github.com/asynkron/protoactor-go/actor"
	cluster "github.com/asynkron/protoactor-go/service/cluster"
	grainactor "github.com/asynkron/protoactor-go/service/grainactor"
	proto "google.golang.org/protobuf/proto"
	slog "log/slog"
)

const ActorKindNameCrossSns = "player_equip"
const ActorNodeTypeCrossSns = "game"
const ActorGroupNameCrossSns = "player"

var xCrossSnsFactory func() CrossSns

// CrossSnsFactory produces a CrossSns
func CrossSnsFactory(factory func() CrossSns) {
	xCrossSnsFactory = factory
}

// GetCrossSnsGrainClient instantiates a new CrossSnsGrainClient with given Identity
func GetCrossSnsGrainClient(c *cluster.Cluster, id string) *CrossSnsGrainClient {
	if c == nil {
		panic(fmt.Errorf("nil cluster instance"))
	}
	if id == "" {
		panic(fmt.Errorf("empty id"))
	}
	return &CrossSnsGrainClient{Identity: id, cluster: c}
}

// GetCrossSnsKind instantiates a new cluster.Kind for CrossSns

// GetCrossSnsKind instantiates a new cluster.Kind for CrossSns

// CrossSns interfaces the services available to the CrossSns
type CrossSns interface {
	RoleSimple(ctx context.Context, req *RoleSimpleRequest) (*RoleSimpleResponse, error)

	Keepalive(ctx context.Context, req *KeepaliveRequest) error
}

// CrossSnsGrainClient holds the base data for the CrossSnsGrain
type CrossSnsGrainClient struct {
	Identity string
	cluster  *cluster.Cluster
}

// BaseCrossSnsGrainClient provides shared cluster access and default call options for CrossSns grains.
type BaseCrossSnsGrainClient struct {
	ClusterFn func() *cluster.Cluster
	Opts      []cluster.GrainCallOption
}

// NewBaseCrossSnsGrainClient creates a BaseCrossSnsGrainClient with default call options.
func NewBaseCrossSnsGrainClient(c func() *cluster.Cluster, opts ...cluster.GrainCallOption) *BaseCrossSnsGrainClient {
	return &BaseCrossSnsGrainClient{ClusterFn: c, Opts: opts}
}

// RoleSimple requests the execution on the cluster.
func (h *BaseCrossSnsGrainClient) RoleSimple(identity string, r *RoleSimpleRequest, opts ...cluster.GrainCallOption) (*RoleSimpleResponse, error) {
	cli := GetCrossSnsGrainClient(h.ClusterFn(), identity)
	return cli.RoleSimple(identity, r, h.mergeOpts(opts)...)
}

// KeepaliveSend delivers a one-way grain message without waiting for a response.
func (h *BaseCrossSnsGrainClient) KeepaliveSend(identity string, r *KeepaliveRequest, opts ...cluster.GrainCallOption) error {
	cli := GetCrossSnsGrainClient(h.ClusterFn(), identity)
	return cli.KeepaliveSend(identity, r, h.mergeOpts(opts)...)
}

func (h *BaseCrossSnsGrainClient) mergeOpts(opts []cluster.GrainCallOption) []cluster.GrainCallOption {
	if len(h.Opts) == 0 {
		return opts
	}
	merged := make([]cluster.GrainCallOption, 0, len(h.Opts)+len(opts))
	merged = append(merged, h.Opts...)
	merged = append(merged, opts...)
	return merged
}

// RoleSimple requests the execution on to the cluster with CallOptions
func (g *CrossSnsGrainClient) RoleSimple(identity string, r *RoleSimpleRequest, opts ...cluster.GrainCallOption) (*RoleSimpleResponse, error) {
	routeKey, err := routeKeyFromServerIDOptions(opts)
	if err != nil {
		return nil, err
	}
	return g.RoleSimpleByRouteKey(identity, routeKey, r, opts...)
}

func (g *CrossSnsGrainClient) RoleSimpleByRouteKey(identity string, routeKey uint64, r *RoleSimpleRequest, opts ...cluster.GrainCallOption) (*RoleSimpleResponse, error) {
	placementContext := &cluster.PlacementContext{NodeType: "game", RouteKey: routeKey}
	return g.RoleSimpleWithPlacementAndRouteKey(placementContext, routeKey, identity, r, opts...)
}

func (g *CrossSnsGrainClient) RoleSimpleWithPlacement(placementContext *cluster.PlacementContext, identity string, r *RoleSimpleRequest, opts ...cluster.GrainCallOption) (*RoleSimpleResponse, error) {
	if g.cluster.Config.RequestLog {
		g.cluster.Logger().Info("Requesting", slog.String("identity", g.Identity), slog.String("kind", "CrossSns"), slog.String("method", "RoleSimple"), slog.Any("request", r))
	}
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 0, MessageData: bytes}
	return g.RoleSimpleRequest(placementContext, reqMsg, identity, opts...)

}
func (g *CrossSnsGrainClient) RoleSimpleWithPlacementAndRouteKey(placementContext *cluster.PlacementContext, routeKey uint64, identity string, r *RoleSimpleRequest, opts ...cluster.GrainCallOption) (*RoleSimpleResponse, error) {
	if g.cluster.Config.RequestLog {
		g.cluster.Logger().Info("Requesting", slog.String("identity", g.Identity), slog.String("kind", "CrossSns"), slog.String("method", "RoleSimple"), slog.Any("request", r))
	}
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 0, MessageData: bytes, RouteKey: routeKey, HasRouteKey: true}
	return g.RoleSimpleRequest(placementContext, reqMsg, identity, opts...)
}

func (g *CrossSnsGrainClient) RoleSimpleRequest(placementContext *cluster.PlacementContext, reqMsg *cluster.GrainRequest, identity string, opts ...cluster.GrainCallOption) (*RoleSimpleResponse, error) {
	resp, err := g.cluster.Request(placementContext, identity, ActorKindNameCrossSns, reqMsg, opts...)
	if err != nil {
		return nil, fmt.Errorf("error request: %w", err)
	}
	switch msg := resp.(type) {
	case *RoleSimpleResponse:
		return msg, nil
	case *cluster.GrainErrorResponse:
		if msg == nil {
			return nil, nil
		}
		return nil, msg
	default:
		return nil, fmt.Errorf("unknown response type %T", resp)
	}
}

// KeepaliveSend delivers a one-way grain message without waiting for a response.
func (g *CrossSnsGrainClient) KeepaliveSend(identity string, r *KeepaliveRequest, opts ...cluster.GrainCallOption) error {
	routeKey, err := routeKeyFromServerIDOptions(opts)
	if err != nil {
		return err
	}
	return g.KeepaliveSendByRouteKey(identity, routeKey, r, opts...)
}
func (g *CrossSnsGrainClient) KeepaliveSendByRouteKey(identity string, routeKey uint64, r *KeepaliveRequest, opts ...cluster.GrainCallOption) error {
	placementContext := &cluster.PlacementContext{NodeType: "game", RouteKey: routeKey}
	return g.KeepaliveSendWithPlacementAndRouteKey(placementContext, routeKey, identity, r, opts...)
}

func (g *CrossSnsGrainClient) KeepaliveSendWithPlacement(placementContext *cluster.PlacementContext, identity string, r *KeepaliveRequest, opts ...cluster.GrainCallOption) error {
	return g.KeepaliveSendWithPlacementAndRouteKey(placementContext, 0, identity, r, opts...)
}

func (g *CrossSnsGrainClient) KeepaliveSendWithPlacementAndRouteKey(placementContext *cluster.PlacementContext, routeKey uint64, identity string, r *KeepaliveRequest, opts ...cluster.GrainCallOption) error {
	if g.cluster.Config.RequestLog {
		g.cluster.Logger().Info("Sending", slog.String("identity", g.Identity), slog.String("kind", "CrossSns"), slog.String("method", "Keepalive"), slog.Any("request", r))
	}
	bytes, err := proto.Marshal(r)
	if err != nil {
		return err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 1, MessageData: bytes, OneWay: true, RouteKey: routeKey, HasRouteKey: true}
	return g.cluster.Send(placementContext, identity, ActorKindNameCrossSns, reqMsg, opts...)
}

const ActorKindNameCrossMail = "player_equip"
const ActorNodeTypeCrossMail = "game"
const ActorGroupNameCrossMail = "player"

var xCrossMailFactory func() CrossMail

// CrossMailFactory produces a CrossMail
func CrossMailFactory(factory func() CrossMail) {
	xCrossMailFactory = factory
}

// GetCrossMailGrainClient instantiates a new CrossMailGrainClient with given Identity
func GetCrossMailGrainClient(c *cluster.Cluster, id string) *CrossMailGrainClient {
	if c == nil {
		panic(fmt.Errorf("nil cluster instance"))
	}
	if id == "" {
		panic(fmt.Errorf("empty id"))
	}
	return &CrossMailGrainClient{Identity: id, cluster: c}
}

// GetCrossMailKind instantiates a new cluster.Kind for CrossMail

// GetCrossMailKind instantiates a new cluster.Kind for CrossMail

// CrossMail interfaces the services available to the CrossMail
type CrossMail interface {
	LoadMail(ctx context.Context, req *LoadMailRequest) (*LoadMailResponse, error)
}

// CrossMailGrainClient holds the base data for the CrossMailGrain
type CrossMailGrainClient struct {
	Identity string
	cluster  *cluster.Cluster
}

// BaseCrossMailGrainClient provides shared cluster access and default call options for CrossMail grains.
type BaseCrossMailGrainClient struct {
	ClusterFn func() *cluster.Cluster
	Opts      []cluster.GrainCallOption
}

// NewBaseCrossMailGrainClient creates a BaseCrossMailGrainClient with default call options.
func NewBaseCrossMailGrainClient(c func() *cluster.Cluster, opts ...cluster.GrainCallOption) *BaseCrossMailGrainClient {
	return &BaseCrossMailGrainClient{ClusterFn: c, Opts: opts}
}

// LoadMail requests the execution on the cluster.
func (h *BaseCrossMailGrainClient) LoadMail(identity string, r *LoadMailRequest, opts ...cluster.GrainCallOption) (*LoadMailResponse, error) {
	cli := GetCrossMailGrainClient(h.ClusterFn(), identity)
	return cli.LoadMail(identity, r, h.mergeOpts(opts)...)
}

func (h *BaseCrossMailGrainClient) mergeOpts(opts []cluster.GrainCallOption) []cluster.GrainCallOption {
	if len(h.Opts) == 0 {
		return opts
	}
	merged := make([]cluster.GrainCallOption, 0, len(h.Opts)+len(opts))
	merged = append(merged, h.Opts...)
	merged = append(merged, opts...)
	return merged
}

// LoadMail requests the execution on to the cluster with CallOptions
func (g *CrossMailGrainClient) LoadMail(identity string, r *LoadMailRequest, opts ...cluster.GrainCallOption) (*LoadMailResponse, error) {
	routeKey, err := routeKeyFromServerIDOptions(opts)
	if err != nil {
		return nil, err
	}
	return g.LoadMailByRouteKey(identity, routeKey, r, opts...)
}

func (g *CrossMailGrainClient) LoadMailByRouteKey(identity string, routeKey uint64, r *LoadMailRequest, opts ...cluster.GrainCallOption) (*LoadMailResponse, error) {
	placementContext := &cluster.PlacementContext{NodeType: "game", RouteKey: routeKey}
	return g.LoadMailWithPlacementAndRouteKey(placementContext, routeKey, identity, r, opts...)
}

func (g *CrossMailGrainClient) LoadMailWithPlacement(placementContext *cluster.PlacementContext, identity string, r *LoadMailRequest, opts ...cluster.GrainCallOption) (*LoadMailResponse, error) {
	if g.cluster.Config.RequestLog {
		g.cluster.Logger().Info("Requesting", slog.String("identity", g.Identity), slog.String("kind", "CrossMail"), slog.String("method", "LoadMail"), slog.Any("request", r))
	}
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 2, MessageData: bytes}
	return g.LoadMailRequest(placementContext, reqMsg, identity, opts...)

}
func (g *CrossMailGrainClient) LoadMailWithPlacementAndRouteKey(placementContext *cluster.PlacementContext, routeKey uint64, identity string, r *LoadMailRequest, opts ...cluster.GrainCallOption) (*LoadMailResponse, error) {
	if g.cluster.Config.RequestLog {
		g.cluster.Logger().Info("Requesting", slog.String("identity", g.Identity), slog.String("kind", "CrossMail"), slog.String("method", "LoadMail"), slog.Any("request", r))
	}
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 2, MessageData: bytes, RouteKey: routeKey, HasRouteKey: true}
	return g.LoadMailRequest(placementContext, reqMsg, identity, opts...)
}

func (g *CrossMailGrainClient) LoadMailRequest(placementContext *cluster.PlacementContext, reqMsg *cluster.GrainRequest, identity string, opts ...cluster.GrainCallOption) (*LoadMailResponse, error) {
	resp, err := g.cluster.Request(placementContext, identity, ActorKindNameCrossMail, reqMsg, opts...)
	if err != nil {
		return nil, fmt.Errorf("error request: %w", err)
	}
	switch msg := resp.(type) {
	case *LoadMailResponse:
		return msg, nil
	case *cluster.GrainErrorResponse:
		if msg == nil {
			return nil, nil
		}
		return nil, msg
	default:
		return nil, fmt.Errorf("unknown response type %T", resp)
	}
}

type PlayerActor interface {
	CrossSns
	CrossMail
}

type playerHandler struct {
	handler PlayerActor
}

type playerServerIDKey struct{}

// WithServerIDKey routes player actor calls by server_id.
func WithServerIDKey(serverID uint64) cluster.GrainCallOption {
	return cluster.WithRouteKey(serverID)
}

// GetServerIDKey returns the server_id route key from ctx.
func GetServerIDKey(ctx context.Context) (uint64, error) {
	serverID, ok := ctx.Value(playerServerIDKey{}).(uint64)
	if !ok {
		return 0, fmt.Errorf("missing route key server_id")
	}

	return serverID, nil
}

func routeKeyFromServerIDOptions(opts []cluster.GrainCallOption) (uint64, error) {
	config := &cluster.GrainCallConfig{}
	for _, opt := range opts {
		opt(config)
	}
	if !config.HasRouteKey {
		return 0, fmt.Errorf("missing route key option WithServerIDKey")
	}

	return config.RouteKey, nil
}

func (h *playerHandler) Receive(ctx grainactor.Context, req *cluster.GrainRequest) (proto.Message, error) {
	switch req.MethodIndex {
	case 0:
		msg := &RoleSimpleRequest{}
		if err := proto.Unmarshal(req.MessageData, msg); err != nil {
			return nil, cluster.NewGrainErrorResponse(cluster.ErrorReason_INVALID_ARGUMENT, err.Error()).
				WithMetadata(map[string]string{
					"argument": msg.String(),
				})
		}
		if !req.HasRouteKey {
			return nil, fmt.Errorf("missing route key server_id")
		}
		handlerCtx := grainactor.ToContext(ctx, grainactor.WithValue(playerServerIDKey{}, req.RouteKey))
		return h.handler.RoleSimple(handlerCtx, msg)
	case 1:
		msg := &KeepaliveRequest{}
		if err := proto.Unmarshal(req.MessageData, msg); err != nil {
			return nil, cluster.NewGrainErrorResponse(cluster.ErrorReason_INVALID_ARGUMENT, err.Error()).
				WithMetadata(map[string]string{
					"argument": msg.String(),
				})
		}
		if !req.HasRouteKey {
			return nil, fmt.Errorf("missing route key server_id")
		}
		handlerCtx := grainactor.ToContext(ctx, grainactor.WithValue(playerServerIDKey{}, req.RouteKey))
		if err := h.handler.Keepalive(handlerCtx, msg); err != nil {
			return nil, err
		}
		return nil, nil
	case 2:
		msg := &LoadMailRequest{}
		if err := proto.Unmarshal(req.MessageData, msg); err != nil {
			return nil, cluster.NewGrainErrorResponse(cluster.ErrorReason_INVALID_ARGUMENT, err.Error()).
				WithMetadata(map[string]string{
					"argument": msg.String(),
				})
		}
		if !req.HasRouteKey {
			return nil, fmt.Errorf("missing route key server_id")
		}
		handlerCtx := grainactor.ToContext(ctx, grainactor.WithValue(playerServerIDKey{}, req.RouteKey))
		return h.handler.LoadMail(handlerCtx, msg)
	default:
		return nil, cluster.NewGrainErrorResponse(cluster.ErrorReason_NOT_FOUND, fmt.Sprintf("unknown grain method index %d", req.MethodIndex))
	}
}

func NewPlayerBaseActor(handler PlayerActor, state any, opts ...grainactor.Option) actor.Actor {
	if state != nil {
		opts = append(opts, grainactor.WithState(state))
	}
	return grainactor.NewBaseActor("player", "player_equip", &playerHandler{handler: handler}, opts...)
}

func NewPlayerKind(handler PlayerActor, state any, opts ...actor.PropsOption) *cluster.Kind {
	props := actor.PropsFromProducer(func() actor.Actor {
		return NewPlayerBaseActor(handler, state)
	}, opts...)
	return cluster.NewKind("player_equip", props)
}

func respond[T proto.Message](ctx cluster.GrainContext) func(T) {
	return func(resp T) {
		ctx.Respond(resp)
	}
}
