// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: test/grainactor/grainactor.proto

package grainactor

import (
	_ "github.com/asynkron/protoactor-go/service/protobuf/protoc-gen-go-grain/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleSimpleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      uint64                 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleSimpleRequest) Reset() {
	*x = RoleSimpleRequest{}
	mi := &file_test_grainactor_grainactor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleSimpleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleSimpleRequest) ProtoMessage() {}

func (x *RoleSimpleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_grainactor_grainactor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleSimpleRequest.ProtoReflect.Descriptor instead.
func (*RoleSimpleRequest) Descriptor() ([]byte, []int) {
	return file_test_grainactor_grainactor_proto_rawDescGZIP(), []int{0}
}

func (x *RoleSimpleRequest) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type RoleSimpleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleSimpleResponse) Reset() {
	*x = RoleSimpleResponse{}
	mi := &file_test_grainactor_grainactor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleSimpleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleSimpleResponse) ProtoMessage() {}

func (x *RoleSimpleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_grainactor_grainactor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleSimpleResponse.ProtoReflect.Descriptor instead.
func (*RoleSimpleResponse) Descriptor() ([]byte, []int) {
	return file_test_grainactor_grainactor_proto_rawDescGZIP(), []int{1}
}

func (x *RoleSimpleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type KeepaliveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      uint64                 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepaliveRequest) Reset() {
	*x = KeepaliveRequest{}
	mi := &file_test_grainactor_grainactor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepaliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepaliveRequest) ProtoMessage() {}

func (x *KeepaliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_grainactor_grainactor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepaliveRequest.ProtoReflect.Descriptor instead.
func (*KeepaliveRequest) Descriptor() ([]byte, []int) {
	return file_test_grainactor_grainactor_proto_rawDescGZIP(), []int{2}
}

func (x *KeepaliveRequest) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type KeepaliveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepaliveResponse) Reset() {
	*x = KeepaliveResponse{}
	mi := &file_test_grainactor_grainactor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepaliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepaliveResponse) ProtoMessage() {}

func (x *KeepaliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_grainactor_grainactor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepaliveResponse.ProtoReflect.Descriptor instead.
func (*KeepaliveResponse) Descriptor() ([]byte, []int) {
	return file_test_grainactor_grainactor_proto_rawDescGZIP(), []int{3}
}

func (x *KeepaliveResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

type LoadMailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      uint64                 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadMailRequest) Reset() {
	*x = LoadMailRequest{}
	mi := &file_test_grainactor_grainactor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMailRequest) ProtoMessage() {}

func (x *LoadMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_grainactor_grainactor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMailRequest.ProtoReflect.Descriptor instead.
func (*LoadMailRequest) Descriptor() ([]byte, []int) {
	return file_test_grainactor_grainactor_proto_rawDescGZIP(), []int{4}
}

func (x *LoadMailRequest) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type LoadMailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadMailResponse) Reset() {
	*x = LoadMailResponse{}
	mi := &file_test_grainactor_grainactor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadMailResponse) ProtoMessage() {}

func (x *LoadMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_grainactor_grainactor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadMailResponse.ProtoReflect.Descriptor instead.
func (*LoadMailResponse) Descriptor() ([]byte, []int) {
	return file_test_grainactor_grainactor_proto_rawDescGZIP(), []int{5}
}

func (x *LoadMailResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_test_grainactor_grainactor_proto protoreflect.FileDescriptor

const file_test_grainactor_grainactor_proto_rawDesc = "" +
	"\n" +
	" test/grainactor/grainactor.proto\x12\n" +
	"grainactor\x1a:service/protobuf/protoc-gen-go-grain/options/options.proto\"0\n" +
	"\x11RoleSimpleRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x04R\bserverId\".\n" +
	"\x12RoleSimpleResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"/\n" +
	"\x10KeepaliveRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x04R\bserverId\"4\n" +
	"\x11KeepaliveResponse\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\".\n" +
	"\x0fLoadMailRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x04R\bserverId\"(\n" +
	"\x10LoadMailResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count2\xb7\x01\n" +
	"\bCrossSns\x12M\n" +
	"\n" +
	"RoleSimple\x12\x1d.grainactor.RoleSimpleRequest\x1a\x1e.grainactor.RoleSimpleResponse\"\x00\x12P\n" +
	"\tKeepalive\x12\x1c.grainactor.KeepaliveRequest\x1a\x1d.grainactor.KeepaliveResponse\"\x06\x82\xb5\x18\x02\x18\x01\x1a\n" +
	"\x82\xb5\x18\x06player2`\n" +
	"\tCrossMail\x12G\n" +
	"\bLoadMail\x12\x1b.grainactor.LoadMailRequest\x1a\x1c.grainactor.LoadMailResponse\"\x00\x1a\n" +
	"\x82\xb5\x18\x06playerB\x83\x01\x82\xb5\x18'\n" +
	"\x06player\x12\fplayer_equip\x1a\x04game\"\tserver_idZVgithub.com/asynkron/protoactor-go/service/protobuf/protoc-gen-go-grain/test/grainactorb\x06proto3"

var (
	file_test_grainactor_grainactor_proto_rawDescOnce sync.Once
	file_test_grainactor_grainactor_proto_rawDescData []byte
)

func file_test_grainactor_grainactor_proto_rawDescGZIP() []byte {
	file_test_grainactor_grainactor_proto_rawDescOnce.Do(func() {
		file_test_grainactor_grainactor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_grainactor_grainactor_proto_rawDesc), len(file_test_grainactor_grainactor_proto_rawDesc)))
	})
	return file_test_grainactor_grainactor_proto_rawDescData
}

var file_test_grainactor_grainactor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_test_grainactor_grainactor_proto_goTypes = []any{
	(*RoleSimpleRequest)(nil),  // 0: grainactor.RoleSimpleRequest
	(*RoleSimpleResponse)(nil), // 1: grainactor.RoleSimpleResponse
	(*KeepaliveRequest)(nil),   // 2: grainactor.KeepaliveRequest
	(*KeepaliveResponse)(nil),  // 3: grainactor.KeepaliveResponse
	(*LoadMailRequest)(nil),    // 4: grainactor.LoadMailRequest
	(*LoadMailResponse)(nil),   // 5: grainactor.LoadMailResponse
}
var file_test_grainactor_grainactor_proto_depIdxs = []int32{
	0, // 0: grainactor.CrossSns.RoleSimple:input_type -> grainactor.RoleSimpleRequest
	2, // 1: grainactor.CrossSns.Keepalive:input_type -> grainactor.KeepaliveRequest
	4, // 2: grainactor.CrossMail.LoadMail:input_type -> grainactor.LoadMailRequest
	1, // 3: grainactor.CrossSns.RoleSimple:output_type -> grainactor.RoleSimpleResponse
	3, // 4: grainactor.CrossSns.Keepalive:output_type -> grainactor.KeepaliveResponse
	5, // 5: grainactor.CrossMail.LoadMail:output_type -> grainactor.LoadMailResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_grainactor_grainactor_proto_init() }
func file_test_grainactor_grainactor_proto_init() {
	if File_test_grainactor_grainactor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_grainactor_grainactor_proto_rawDesc), len(file_test_grainactor_grainactor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_test_grainactor_grainactor_proto_goTypes,
		DependencyIndexes: file_test_grainactor_grainactor_proto_depIdxs,
		MessageInfos:      file_test_grainactor_grainactor_proto_msgTypes,
	}.Build()
	File_test_grainactor_grainactor_proto = out.File
	file_test_grainactor_grainactor_proto_goTypes = nil
	file_test_grainactor_grainactor_proto_depIdxs = nil
}
