syntax = "proto3";

package grainactor;

import "service/protobuf/protoc-gen-go-grain/options/options.proto";

option go_package = "github.com/asynkron/protoactor-go/service/protobuf/protoc-gen-go-grain/test/grainactor";
option (options.actor_base) = {
  actor: "player"
  kind: "player_equip"
  node_type: "game"
  field: "server_id"
};

message RoleSimpleRequest {
  uint64 server_id = 1;
}

message RoleSimpleResponse {
  string message = 1;
}

message KeepaliveRequest {
  uint64 server_id = 1;
}

message KeepaliveResponse {
  int64 server_time = 1;
}

message LoadMailRequest {
  uint64 server_id = 1;
}

message LoadMailResponse {
  int32 count = 1;
}

service CrossSns {
  option (options.actor) = "player";

  rpc RoleSimple(RoleSimpleRequest) returns (RoleSimpleResponse) {}
  rpc Keepalive(KeepaliveRequest) returns (KeepaliveResponse) {
    option (options.method_options) = { oneway: true };
  }
}

service CrossMail {
  option (options.actor) = "player";

  rpc LoadMail(LoadMailRequest) returns (LoadMailResponse) {}
}
