// Code generated by protoc-gen-grain. DO NOT EDIT.
// versions:
//  protoc-gen-grain v0.7.0
//  protoc           v7.34.1
// source: test/error/error.proto

package hello

import (
	fmt "fmt"
	cluster "github.com/asynkron/protoactor-go/service/cluster"
)

func ErrUserNotFound(format string, args ...interface{}) *cluster.GrainErrorResponse {
	return cluster.NewGrainErrorResponse(ErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := cluster.FromError(err)
	return e.Reason == ErrorReason_USER_NOT_FOUND.String()
}

func ErrContentMissing(format string, args ...interface{}) *cluster.GrainErrorResponse {
	return cluster.NewGrainErrorResponse(ErrorReason_CONTENT_MISSING.String(), fmt.Sprintf(format, args...))
}

func IsContentMissing(err error) bool {
	if err == nil {
		return false
	}
	e := cluster.FromError(err)
	return e.Reason == ErrorReason_CONTENT_MISSING.String()
}
