// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: test/error/error.proto

package hello

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_USER_NOT_FOUND  ErrorReason = 0
	ErrorReason_CONTENT_MISSING ErrorReason = 1
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "USER_NOT_FOUND",
		1: "CONTENT_MISSING",
	}
	ErrorReason_value = map[string]int32{
		"USER_NOT_FOUND":  0,
		"CONTENT_MISSING": 1,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_test_error_error_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_test_error_error_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_test_error_error_proto_rawDescGZIP(), []int{0}
}

var File_test_error_error_proto protoreflect.FileDescriptor

const file_test_error_error_proto_rawDesc = "" +
	"\n" +
	"\x16test/error/error.proto\x12\x05hello*6\n" +
	"\vErrorReason\x12\x12\n" +
	"\x0eUSER_NOT_FOUND\x10\x00\x12\x13\n" +
	"\x0fCONTENT_MISSING\x10\x01BFZDgithub.com/asynkron/protoactor-go/protoc-gen-go-grain/testdata/hellob\x06proto3"

var (
	file_test_error_error_proto_rawDescOnce sync.Once
	file_test_error_error_proto_rawDescData []byte
)

func file_test_error_error_proto_rawDescGZIP() []byte {
	file_test_error_error_proto_rawDescOnce.Do(func() {
		file_test_error_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_error_error_proto_rawDesc), len(file_test_error_error_proto_rawDesc)))
	})
	return file_test_error_error_proto_rawDescData
}

var file_test_error_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_error_error_proto_goTypes = []any{
	(ErrorReason)(0), // 0: hello.ErrorReason
}
var file_test_error_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_error_error_proto_init() }
func file_test_error_error_proto_init() {
	if File_test_error_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_error_error_proto_rawDesc), len(file_test_error_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_error_error_proto_goTypes,
		DependencyIndexes: file_test_error_error_proto_depIdxs,
		EnumInfos:         file_test_error_error_proto_enumTypes,
	}.Build()
	File_test_error_error_proto = out.File
	file_test_error_error_proto_goTypes = nil
	file_test_error_error_proto_depIdxs = nil
}
