// Code generated by protoc-gen-grain. DO NOT EDIT.

package hello

import (
	cluster "github.com/asynkron/protoactor-go/service/cluster"
)

var (
	allServiceGrainClients = &allServiceGrainClientSet{}
)

type allServiceGrainClientSet struct {
	baseHelloGrainClient *BaseHelloGrainClient
}

// InitServiceGrainClients initializes shared base grain clients for all generated grain services.
func InitServiceGrainClients(fn func() *cluster.Cluster, opts ...cluster.GrainCallOption) {
	allServiceGrainClients.baseHelloGrainClient = NewBaseHelloGrainClient(fn, opts...)
}

// GetBaseHelloGrainClient returns the shared base client for Hello.
func GetBaseHelloGrainClient() *BaseHelloGrainClient {
	return allServiceGrainClients.baseHelloGrainClient
}
