// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: test/reenter/hello.proto

package hello

import (
	_ "github.com/asynkron/protoactor-go/service/protobuf/protoc-gen-go-grain/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_test_reenter_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_reenter_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_test_reenter_hello_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_test_reenter_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_reenter_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_test_reenter_hello_proto_rawDescGZIP(), []int{1}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DoworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoworkRequest) Reset() {
	*x = DoworkRequest{}
	mi := &file_test_reenter_hello_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoworkRequest) ProtoMessage() {}

func (x *DoworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_reenter_hello_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoworkRequest.ProtoReflect.Descriptor instead.
func (*DoworkRequest) Descriptor() ([]byte, []int) {
	return file_test_reenter_hello_proto_rawDescGZIP(), []int{2}
}

func (x *DoworkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DoworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoworkResponse) Reset() {
	*x = DoworkResponse{}
	mi := &file_test_reenter_hello_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoworkResponse) ProtoMessage() {}

func (x *DoworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_reenter_hello_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoworkResponse.ProtoReflect.Descriptor instead.
func (*DoworkResponse) Descriptor() ([]byte, []int) {
	return file_test_reenter_hello_proto_rawDescGZIP(), []int{3}
}

func (x *DoworkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_test_reenter_hello_proto protoreflect.FileDescriptor

const file_test_reenter_hello_proto_rawDesc = "" +
	"\n" +
	"\x18test/reenter/hello.proto\x12\x05hello\x1a:service/protobuf/protoc-gen-go-grain/options/options.proto\"%\n" +
	"\x0fSayHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x10SayHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"#\n" +
	"\rDoworkRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"*\n" +
	"\x0eDoworkResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x8b\x01\n" +
	"\x05Hello\x12C\n" +
	"\bSayHello\x12\x16.hello.SayHelloRequest\x1a\x17.hello.SayHelloResponse\"\x06\x82\xb5\x18\x02\b\x01\x12=\n" +
	"\x06Dowork\x12\x14.hello.DoworkRequest\x1a\x15.hello.DoworkResponse\"\x06\x82\xb5\x18\x02\x10\x01BFZDgithub.com/asynkron/protoactor-go/protoc-gen-go-grain/testdata/hellob\x06proto3"

var (
	file_test_reenter_hello_proto_rawDescOnce sync.Once
	file_test_reenter_hello_proto_rawDescData []byte
)

func file_test_reenter_hello_proto_rawDescGZIP() []byte {
	file_test_reenter_hello_proto_rawDescOnce.Do(func() {
		file_test_reenter_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_reenter_hello_proto_rawDesc), len(file_test_reenter_hello_proto_rawDesc)))
	})
	return file_test_reenter_hello_proto_rawDescData
}

var file_test_reenter_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_test_reenter_hello_proto_goTypes = []any{
	(*SayHelloRequest)(nil),  // 0: hello.SayHelloRequest
	(*SayHelloResponse)(nil), // 1: hello.SayHelloResponse
	(*DoworkRequest)(nil),    // 2: hello.DoworkRequest
	(*DoworkResponse)(nil),   // 3: hello.DoworkResponse
}
var file_test_reenter_hello_proto_depIdxs = []int32{
	0, // 0: hello.Hello.SayHello:input_type -> hello.SayHelloRequest
	2, // 1: hello.Hello.Dowork:input_type -> hello.DoworkRequest
	1, // 2: hello.Hello.SayHello:output_type -> hello.SayHelloResponse
	3, // 3: hello.Hello.Dowork:output_type -> hello.DoworkResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_reenter_hello_proto_init() }
func file_test_reenter_hello_proto_init() {
	if File_test_reenter_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_reenter_hello_proto_rawDesc), len(file_test_reenter_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_reenter_hello_proto_goTypes,
		DependencyIndexes: file_test_reenter_hello_proto_depIdxs,
		MessageInfos:      file_test_reenter_hello_proto_msgTypes,
	}.Build()
	File_test_reenter_hello_proto = out.File
	file_test_reenter_hello_proto_goTypes = nil
	file_test_reenter_hello_proto_depIdxs = nil
}
