// Package main implements protoc-gen-go-grain.
package main

import (
	"errors"
	"fmt"
	"sort"
	"strings"

	"github.com/asynkron/protoactor-go/service/protobuf/protoc-gen-go-grain/options"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

func setClusterImportPath(value string) error {
	if value == "" {
		return errors.New("cluster_import cannot be empty")
	}
	clusterImportPath = value

	return nil
}

const deprecationComment = "// Deprecated: Do not use."

const (
	legacyClusterImportPath  = "github.com/asynkron/protoactor-go/cluster"
	serviceClusterImportPath = "github.com/asynkron/protoactor-go/service/cluster"

	timePackage       = protogen.GoImportPath("time")
	contextPackage    = protogen.GoImportPath("context")
	errorsPackage     = protogen.GoImportPath("errors")
	fmtPackage        = protogen.GoImportPath("fmt")
	slogPackage       = protogen.GoImportPath("log/slog")
	protoPackage      = protogen.GoImportPath("google.golang.org/protobuf/proto")
	actorPackage      = protogen.GoImportPath("github.com/asynkron/protoactor-go/actor")
	grainactorPackage = protogen.GoImportPath("github.com/asynkron/protoactor-go/service/grainactor")
)

var (
	noLowerCaser = cases.Title(language.AmericanEnglish, cases.NoLower)
	caser        = cases.Title(language.AmericanEnglish)

	clusterImportPath = serviceClusterImportPath
)

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	if len(file.Services) == 0 && len(file.Enums) == 0 {
		return
	}

	filename := file.GeneratedFilenamePrefix + "_grain.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	generateHeader(gen, g, file)
	generateContent(gen, g, file)
}

func generateHeader(gen *protogen.Plugin, g *protogen.GeneratedFile, file *protogen.File) {
	g.P("// Code generated by protoc-gen-grain. DO NOT EDIT.")
	g.P("// versions:")
	g.P("//  protoc-gen-grain ", version)
	protocVersion := "(unknown)"
	if v := gen.Request.GetCompilerVersion(); v != nil {
		protocVersion = fmt.Sprintf("v%v.%v.%v", v.GetMajor(), v.GetMinor(), v.GetPatch())
		if s := v.GetSuffix(); s != "" {
			protocVersion += "-" + s
		}
	}
	g.P("//  protoc           ", protocVersion)
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()
}

func generateContent(gen *protogen.Plugin, g *protogen.GeneratedFile, file *protogen.File) {
	g.P("package ", file.GoPackageName)

	clusterPackage := protogen.GoImportPath(clusterImportPath)
	g.QualifiedGoIdent(clusterPackage.Ident(""))
	g.QualifiedGoIdent(fmtPackage.Ident(""))

	for _, enum := range file.Enums {
		if enum.Desc.Name() == "ErrorReason" {
			generateErrorReasons(g, enum)
		}
	}

	if len(file.Services) == 0 {
		return
	}

	actorBases, err := collectActorBases(gen)
	if err != nil {
		panic(err)
	}
	services := make([]*serviceDesc, 0, len(file.Services))
	usesGrainactor := false
	usesLegacyActor := false
	for _, service := range file.Services {
		sd, err := buildServiceDesc(service, g, actorBases)
		if err != nil {
			panic(err)
		}
		if len(sd.Methods) != 0 {
			services = append(services, sd)
			usesGrainactor = usesGrainactor || sd.UseGrainactor
			usesLegacyActor = usesLegacyActor || !sd.UseGrainactor
		}
	}

	g.QualifiedGoIdent(actorPackage.Ident(""))
	if usesGrainactor {
		g.QualifiedGoIdent(contextPackage.Ident(""))
		g.QualifiedGoIdent(grainactorPackage.Ident(""))
	}
	g.QualifiedGoIdent(protoPackage.Ident(""))
	if usesLegacyActor {
		g.QualifiedGoIdent(timePackage.Ident(""))
	}
	g.QualifiedGoIdent(slogPackage.Ident(""))

	grainactorServices := make([]*serviceDesc, 0, len(services))
	for _, service := range services {
		if service.UseGrainactor {
			grainactorServices = append(grainactorServices, service)
		}
	}

	actors, err := buildActorDescs(grainactorServices)
	if err != nil {
		panic(err)
	}

	for _, service := range services {
		g.P(service.execute())
		g.P()
	}

	for _, actor := range actors {
		g.P(actor.execute())
		g.P()
	}

	generateRespond(g)
}

func buildServiceDesc(service *protogen.Service, g *protogen.GeneratedFile, actorBases map[string]*options.ActorBase) (*serviceDesc, error) {
	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		g.P("//")
		g.P(deprecationComment)
	}

	useGrainactor := hasServiceOption(service, options.E_Actor)
	sd := &serviceDesc{
		Name:                  service.GoName,
		ClusterImportPath:     clusterImportPath,
		ClusterImportPathName: "cluster",
		UsePlacementContext:   clusterImportPath == serviceClusterImportPath,
		UseGrainactor:         useGrainactor,
	}

	if useGrainactor {
		actor := getServiceStringOption(service, options.E_Actor, "")
		if actor == "" {
			return nil, fmt.Errorf("service %q: option actor must not be empty", service.GoName)
		}
		base, ok := actorBases[actor]
		if !ok {
			return nil, fmt.Errorf("service %q: actor %q not found in file actor_base options", service.GoName, actor)
		}
		sd.Actor = actor
		sd.Kind = base.GetKind()
		sd.NodeType = base.GetNodeType()
		sd.RouteKeyField = base.GetField()
	} else {
		sd.Kind = service.GoName
		sd.Actor = service.GoName
	}

	for i, method := range service.Methods {
		if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
			continue
		}

		methodOptions, ok := proto.GetExtension(method.Desc.Options(), options.E_MethodOptions).(*options.MethodOptions)
		if !ok {
			continue
		}

		if methodOptions == nil {
			methodOptions = &options.MethodOptions{}
		}

		if methodOptions.GetOneway() && methodOptions.GetFuture() {
			return nil, fmt.Errorf("service %q method %q: oneway and future are mutually exclusive", service.GoName, method.GoName)
		}
		if methodOptions.GetOneway() && methodOptions.GetReenterable() {
			return nil, fmt.Errorf("service %q method %q: oneway and reenterable are mutually exclusive", service.GoName, method.GoName)
		}

		md := &methodDesc{
			Name:    method.GoName,
			Input:   g.QualifiedGoIdent(method.Input.GoIdent),
			Output:  g.QualifiedGoIdent(method.Output.GoIdent),
			Index:   i,
			Options: methodOptions,
		}

		sd.Methods = append(sd.Methods, md)
	}

	return sd, nil
}

func collectActorBases(gen *protogen.Plugin) (map[string]*options.ActorBase, error) {
	actorBases := make(map[string]*options.ActorBase)
	if gen == nil {
		return actorBases, nil
	}

	for _, file := range gen.Files {
		if file == nil || file.Desc == nil {
			continue
		}
		values := proto.GetExtension(file.Desc.Options(), options.E_ActorBase)
		bases, ok := values.([]*options.ActorBase)
		if !ok {
			continue
		}
		for i, base := range bases {
			if err := validateActorBase(file.Desc.Path(), i, base); err != nil {
				return nil, err
			}
			if _, exists := actorBases[base.GetActor()]; exists {
				return nil, fmt.Errorf("file %q: duplicate actor_base for actor %q", file.Desc.Path(), base.GetActor())
			}
			actorBases[base.GetActor()] = base
		}
	}

	return actorBases, nil
}

func validateActorBase(filePath string, index int, base *options.ActorBase) error {
	if base.GetActor() == "" {
		return fmt.Errorf("file %q: actor_base[%d] missing required field actor", filePath, index)
	}
	if base.GetKind() == "" {
		return fmt.Errorf("file %q: actor_base[%d] missing required field kind", filePath, index)
	}
	if base.GetNodeType() == "" {
		return fmt.Errorf("file %q: actor_base[%d] missing required field node_type", filePath, index)
	}
	if base.GetField() == "" {
		return fmt.Errorf("file %q: actor_base[%d] missing required field field", filePath, index)
	}

	return nil
}

func getServiceStringOption(service *protogen.Service, extension protoreflect.ExtensionType, defaultValue string) string {
	value := proto.GetExtension(service.Desc.Options(), extension)
	if s, ok := value.(string); ok && s != "" {
		return s
	}

	return defaultValue
}

func hasServiceOption(service *protogen.Service, extension protoreflect.ExtensionType) bool {
	return proto.HasExtension(service.Desc.Options(), extension)
}

func buildActorDescs(services []*serviceDesc) ([]*actorDesc, error) {
	actorsByName := make(map[string]*actorDesc)
	for _, service := range services {
		if service.Kind == "" {
			return nil, fmt.Errorf("service %q resolved empty kind", service.Name)
		}
		actorName := service.Actor
		if actorName == "" {
			actorName = service.Name
		}
		actor := actorsByName[actorName]
		if actor == nil {
			actor = &actorDesc{
				Name:          toCamel(actorName),
				Actor:         actorName,
				Kind:          service.Kind,
				NodeType:      service.NodeType,
				RouteKeyField: service.RouteKeyField,
			}
			actorsByName[actorName] = actor
		}
		for _, existingService := range actor.Services {
			for _, existingMethod := range existingService.Methods {
				for _, method := range service.Methods {
					if existingMethod.Name == method.Name {
						return nil, fmt.Errorf("actor %q has duplicate method %q", actorName, method.Name)
					}
				}
			}
		}
		for _, method := range service.Methods {
			method.Index = len(actor.Methods)
			actor.Methods = append(actor.Methods, &actorMethodDesc{
				Service: service,
				Method:  method,
				Index:   method.Index,
			})
		}
		actor.Services = append(actor.Services, service)
	}

	names := make([]string, 0, len(actorsByName))
	for name := range actorsByName {
		names = append(names, name)
	}
	sort.Strings(names)

	actors := make([]*actorDesc, 0, len(names))
	for _, name := range names {
		actors = append(actors, actorsByName[name])
	}

	return actors, nil
}

func generateRespond(g *protogen.GeneratedFile) {
	g.P("func respond[T proto.Message](ctx cluster.GrainContext) func (T) {")
	g.P("return func (resp T) {")
	g.P("ctx.Respond(resp)")
	g.P("}")
	g.P("}")
}

func generateErrorReasons(g *protogen.GeneratedFile, enum *protogen.Enum) {
	var es errorsWrapper
	for _, v := range enum.Values {
		comment := v.Comments.Leading.String()
		if comment == "" {
			comment = v.Comments.Trailing.String()
		}

		err := &errorDesc{
			Name:       string(enum.Desc.Name()),
			Value:      string(v.Desc.Name()),
			CamelValue: toCamel(string(v.Desc.Name())),
			Comment:    comment,
			HasComment: len(comment) > 0,
		}
		es.Errors = append(es.Errors, err)
	}
	if len(es.Errors) != 0 {
		g.P(es.execute())
	}
}

func toCamel(s string) string {
	if !strings.Contains(s, "_") {
		if s == strings.ToUpper(s) {
			s = strings.ToLower(s)
		}
		return goInitialism(noLowerCaser.String(s))
	}

	slice := strings.Split(s, "_")
	for i := 0; i < len(slice); i++ {
		slice[i] = goInitialism(caser.String(slice[i]))
	}
	return strings.Join(slice, "")
}

func goInitialism(s string) string {
	if strings.EqualFold(s, "id") {
		return "ID"
	}

	return s
}
