// Code generated by protoc-gen-grain. DO NOT EDIT.
// versions:
//  protoc-gen-grain v0.7.0
//  protoc           v7.34.1
// source: test/hello/hello.proto

package hello

import (
	fmt "fmt"
	cluster "github.com/asynkron/protoactor-go/service/cluster"
	proto "google.golang.org/protobuf/proto"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	slog "log/slog"
)

const ActorKindNameHello = "Hello"
const ActorNodeTypeHello = ""
const ActorGroupNameHello = "Hello"

// GetHelloGrainClient instantiates a new HelloGrainClient with given Identity
func GetHelloGrainClient(c *cluster.Cluster, id string) *HelloGrainClient {
	if c == nil {
		panic(fmt.Errorf("nil cluster instance"))
	}
	if id == "" {
		panic(fmt.Errorf("empty id"))
	}
	return &HelloGrainClient{Identity: id, cluster: c}
}

// HelloGrainClient holds the base data for the HelloGrain
type HelloGrainClient struct {
	Identity string
	cluster  *cluster.Cluster
}

// BaseHelloGrainClient provides shared cluster access and default call options for Hello grains.
type BaseHelloGrainClient struct {
	ClusterFn func() *cluster.Cluster
	Opts      []cluster.GrainCallOption
}

// NewBaseHelloGrainClient creates a BaseHelloGrainClient with default call options.
func NewBaseHelloGrainClient(c func() *cluster.Cluster, opts ...cluster.GrainCallOption) *BaseHelloGrainClient {
	return &BaseHelloGrainClient{ClusterFn: c, Opts: opts}
}

// SayHello requests the execution on the cluster.
func (h *BaseHelloGrainClient) SayHello(identity string, placementContext *cluster.PlacementContext, r *emptypb.Empty, opts ...cluster.GrainCallOption) (*SayHelloResponse, error) {
	cli := GetHelloGrainClient(h.ClusterFn(), identity)
	return cli.SayHello(placementContext, r, h.mergeOpts(opts)...)
}

func (h *BaseHelloGrainClient) mergeOpts(opts []cluster.GrainCallOption) []cluster.GrainCallOption {
	if len(h.Opts) == 0 {
		return opts
	}
	merged := make([]cluster.GrainCallOption, 0, len(h.Opts)+len(opts))
	merged = append(merged, h.Opts...)
	merged = append(merged, opts...)
	return merged
}

// SayHello requests the execution on to the cluster with CallOptions
func (g *HelloGrainClient) SayHello(placementContext *cluster.PlacementContext, r *emptypb.Empty, opts ...cluster.GrainCallOption) (*SayHelloResponse, error) {
	if g.cluster.Config.RequestLog {
		g.cluster.Logger().Info("Requesting", slog.String("identity", g.Identity), slog.String("kind", "Hello"), slog.String("method", "SayHello"), slog.Any("request", r))
	}
	bytes, err := proto.Marshal(r)
	if err != nil {
		return nil, err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 0, MessageData: bytes}
	resp, err := g.cluster.Request(placementContext, g.Identity, ActorKindNameHello, reqMsg, opts...)
	if err != nil {
		return nil, fmt.Errorf("error request: %w", err)
	}
	switch msg := resp.(type) {
	case *SayHelloResponse:
		return msg, nil
	case *cluster.GrainErrorResponse:
		if msg == nil {
			return nil, nil
		}
		return nil, msg
	default:
		return nil, fmt.Errorf("unknown response type %T", resp)
	}
}
