// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: test/hello/hello.proto

package hello

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_test_hello_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_hello_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_test_hello_hello_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_test_hello_hello_proto protoreflect.FileDescriptor

const file_test_hello_hello_proto_rawDesc = "" +
	"\n" +
	"\x16test/hello/hello.proto\x12\x05hello\x1a\x1bgoogle/protobuf/empty.proto\",\n" +
	"\x10SayHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2F\n" +
	"\x05Hello\x12=\n" +
	"\bSayHello\x12\x16.google.protobuf.Empty\x1a\x17.hello.SayHelloResponse\"\x00BFZDgithub.com/asynkron/protoactor-go/protoc-gen-go-grain/testdata/hellob\x06proto3"

var (
	file_test_hello_hello_proto_rawDescOnce sync.Once
	file_test_hello_hello_proto_rawDescData []byte
)

func file_test_hello_hello_proto_rawDescGZIP() []byte {
	file_test_hello_hello_proto_rawDescOnce.Do(func() {
		file_test_hello_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_hello_hello_proto_rawDesc), len(file_test_hello_hello_proto_rawDesc)))
	})
	return file_test_hello_hello_proto_rawDescData
}

var file_test_hello_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_hello_hello_proto_goTypes = []any{
	(*SayHelloResponse)(nil), // 0: hello.SayHelloResponse
	(*emptypb.Empty)(nil),    // 1: google.protobuf.Empty
}
var file_test_hello_hello_proto_depIdxs = []int32{
	1, // 0: hello.Hello.SayHello:input_type -> google.protobuf.Empty
	0, // 1: hello.Hello.SayHello:output_type -> hello.SayHelloResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_hello_hello_proto_init() }
func file_test_hello_hello_proto_init() {
	if File_test_hello_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_hello_hello_proto_rawDesc), len(file_test_hello_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_hello_hello_proto_goTypes,
		DependencyIndexes: file_test_hello_hello_proto_depIdxs,
		MessageInfos:      file_test_hello_hello_proto_msgTypes,
	}.Build()
	File_test_hello_hello_proto = out.File
	file_test_hello_hello_proto_goTypes = nil
	file_test_hello_hello_proto_depIdxs = nil
}
