// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: test/multi-services/services.proto

package hello

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_test_multi_services_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_multi_services_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_test_multi_services_services_proto_rawDescGZIP(), []int{0}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DoWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Work          string                 `protobuf:"bytes,1,opt,name=work,proto3" json:"work,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoWorkRequest) Reset() {
	*x = DoWorkRequest{}
	mi := &file_test_multi_services_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoWorkRequest) ProtoMessage() {}

func (x *DoWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_multi_services_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoWorkRequest.ProtoReflect.Descriptor instead.
func (*DoWorkRequest) Descriptor() ([]byte, []int) {
	return file_test_multi_services_services_proto_rawDescGZIP(), []int{1}
}

func (x *DoWorkRequest) GetWork() string {
	if x != nil {
		return x.Work
	}
	return ""
}

type DoWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoWorkResponse) Reset() {
	*x = DoWorkResponse{}
	mi := &file_test_multi_services_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoWorkResponse) ProtoMessage() {}

func (x *DoWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_multi_services_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoWorkResponse.ProtoReflect.Descriptor instead.
func (*DoWorkResponse) Descriptor() ([]byte, []int) {
	return file_test_multi_services_services_proto_rawDescGZIP(), []int{2}
}

func (x *DoWorkResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_test_multi_services_services_proto protoreflect.FileDescriptor

const file_test_multi_services_services_proto_rawDesc = "" +
	"\n" +
	"\"test/multi-services/services.proto\x12\x05hello\x1a\x1bgoogle/protobuf/empty.proto\",\n" +
	"\x10SayHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"#\n" +
	"\rDoWorkRequest\x12\x12\n" +
	"\x04work\x18\x01 \x01(\tR\x04work\"(\n" +
	"\x0eDoWorkResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result2F\n" +
	"\x05Hello\x12=\n" +
	"\bSayHello\x12\x16.google.protobuf.Empty\x1a\x17.hello.SayHelloResponse\"\x002?\n" +
	"\x04Work\x127\n" +
	"\x06DoWork\x12\x14.hello.DoWorkRequest\x1a\x15.hello.DoWorkResponse\"\x00BFZDgithub.com/asynkron/protoactor-go/protoc-gen-go-grain/testdata/hellob\x06proto3"

var (
	file_test_multi_services_services_proto_rawDescOnce sync.Once
	file_test_multi_services_services_proto_rawDescData []byte
)

func file_test_multi_services_services_proto_rawDescGZIP() []byte {
	file_test_multi_services_services_proto_rawDescOnce.Do(func() {
		file_test_multi_services_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_multi_services_services_proto_rawDesc), len(file_test_multi_services_services_proto_rawDesc)))
	})
	return file_test_multi_services_services_proto_rawDescData
}

var file_test_multi_services_services_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_test_multi_services_services_proto_goTypes = []any{
	(*SayHelloResponse)(nil), // 0: hello.SayHelloResponse
	(*DoWorkRequest)(nil),    // 1: hello.DoWorkRequest
	(*DoWorkResponse)(nil),   // 2: hello.DoWorkResponse
	(*emptypb.Empty)(nil),    // 3: google.protobuf.Empty
}
var file_test_multi_services_services_proto_depIdxs = []int32{
	3, // 0: hello.Hello.SayHello:input_type -> google.protobuf.Empty
	1, // 1: hello.Work.DoWork:input_type -> hello.DoWorkRequest
	0, // 2: hello.Hello.SayHello:output_type -> hello.SayHelloResponse
	2, // 3: hello.Work.DoWork:output_type -> hello.DoWorkResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_multi_services_services_proto_init() }
func file_test_multi_services_services_proto_init() {
	if File_test_multi_services_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_multi_services_services_proto_rawDesc), len(file_test_multi_services_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_test_multi_services_services_proto_goTypes,
		DependencyIndexes: file_test_multi_services_services_proto_depIdxs,
		MessageInfos:      file_test_multi_services_services_proto_msgTypes,
	}.Build()
	File_test_multi_services_services_proto = out.File
	file_test_multi_services_services_proto_goTypes = nil
	file_test_multi_services_services_proto_depIdxs = nil
}
