syntax = "proto3";

package options;

import "google/protobuf/descriptor.proto";

option go_package = "github.com/asynkron/protoactor-go/service/protobuf/protoc-gen-go-grain/options";

message MethodOptions {
  // mark a method as reenterable will generate a callback version of the method
  bool reenterable = 1;
  // generate an extra future interface in the client
  // all methods called in reenterable methods should use the future interface
  bool future = 2;
  // generate a fire-and-forget client method that uses cluster.Send
  bool oneway = 3;
}

message ActorBase {
  string actor = 1;
  string kind = 2;
  string node_type = 3;
  string field = 4;
}

extend google.protobuf.MethodOptions {
  MethodOptions method_options = 50000;
}

extend google.protobuf.FileOptions {
  repeated ActorBase actor_base = 50000;
}

extend google.protobuf.ServiceOptions {
  string actor = 50000;
}
