// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: options/options.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MethodOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mark a method as reenterable will generate a callback version of the method
	Reenterable bool `protobuf:"varint,1,opt,name=reenterable,proto3" json:"reenterable,omitempty"`
	// generate an extra future interface in the client
	// all methods called in reenterable methods should use the future interface
	Future bool `protobuf:"varint,2,opt,name=future,proto3" json:"future,omitempty"`
	// generate a fire-and-forget client method that uses cluster.Send
	Oneway        bool `protobuf:"varint,3,opt,name=oneway,proto3" json:"oneway,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	mi := &file_options_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_options_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_options_options_proto_rawDescGZIP(), []int{0}
}

func (x *MethodOptions) GetReenterable() bool {
	if x != nil {
		return x.Reenterable
	}
	return false
}

func (x *MethodOptions) GetFuture() bool {
	if x != nil {
		return x.Future
	}
	return false
}

func (x *MethodOptions) GetOneway() bool {
	if x != nil {
		return x.Oneway
	}
	return false
}

type ActorBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         string                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	NodeType      string                 `protobuf:"bytes,3,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"`
	Field         string                 `protobuf:"bytes,4,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorBase) Reset() {
	*x = ActorBase{}
	mi := &file_options_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorBase) ProtoMessage() {}

func (x *ActorBase) ProtoReflect() protoreflect.Message {
	mi := &file_options_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorBase.ProtoReflect.Descriptor instead.
func (*ActorBase) Descriptor() ([]byte, []int) {
	return file_options_options_proto_rawDescGZIP(), []int{1}
}

func (x *ActorBase) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *ActorBase) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ActorBase) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *ActorBase) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

var file_options_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         50000,
		Name:          "options.method_options",
		Tag:           "bytes,50000,opt,name=method_options",
		Filename:      "options/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: ([]*ActorBase)(nil),
		Field:         50000,
		Name:          "options.actor_base",
		Tag:           "bytes,50000,rep,name=actor_base",
		Filename:      "options/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50000,
		Name:          "options.actor",
		Tag:           "bytes,50000,opt,name=actor",
		Filename:      "options/options.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional options.MethodOptions method_options = 50000;
	E_MethodOptions = &file_options_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// repeated options.ActorBase actor_base = 50000;
	E_ActorBase = &file_options_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional string actor = 50000;
	E_Actor = &file_options_options_proto_extTypes[2]
)

var File_options_options_proto protoreflect.FileDescriptor

const file_options_options_proto_rawDesc = "" +
	"\n" +
	"\x15options/options.proto\x12\aoptions\x1a google/protobuf/descriptor.proto\"a\n" +
	"\rMethodOptions\x12 \n" +
	"\vreenterable\x18\x01 \x01(\bR\vreenterable\x12\x16\n" +
	"\x06future\x18\x02 \x01(\bR\x06future\x12\x16\n" +
	"\x06oneway\x18\x03 \x01(\bR\x06oneway\"h\n" +
	"\tActorBase\x12\x14\n" +
	"\x05actor\x18\x01 \x01(\tR\x05actor\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1b\n" +
	"\tnode_type\x18\x03 \x01(\tR\bnodeType\x12\x14\n" +
	"\x05field\x18\x04 \x01(\tR\x05field:_\n" +
	"\x0emethod_options\x12\x1e.google.protobuf.MethodOptions\x18І\x03 \x01(\v2\x16.options.MethodOptionsR\rmethodOptions:Q\n" +
	"\n" +
	"actor_base\x12\x1c.google.protobuf.FileOptions\x18І\x03 \x03(\v2\x12.options.ActorBaseR\tactorBase:7\n" +
	"\x05actor\x12\x1f.google.protobuf.ServiceOptions\x18І\x03 \x01(\tR\x05actorBPZNgithub.com/asynkron/protoactor-go/service/protobuf/protoc-gen-go-grain/optionsb\x06proto3"

var (
	file_options_options_proto_rawDescOnce sync.Once
	file_options_options_proto_rawDescData []byte
)

func file_options_options_proto_rawDescGZIP() []byte {
	file_options_options_proto_rawDescOnce.Do(func() {
		file_options_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_options_options_proto_rawDesc), len(file_options_options_proto_rawDesc)))
	})
	return file_options_options_proto_rawDescData
}

var file_options_options_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_options_options_proto_goTypes = []any{
	(*MethodOptions)(nil),               // 0: options.MethodOptions
	(*ActorBase)(nil),                   // 1: options.ActorBase
	(*descriptorpb.MethodOptions)(nil),  // 2: google.protobuf.MethodOptions
	(*descriptorpb.FileOptions)(nil),    // 3: google.protobuf.FileOptions
	(*descriptorpb.ServiceOptions)(nil), // 4: google.protobuf.ServiceOptions
}
var file_options_options_proto_depIdxs = []int32{
	2, // 0: options.method_options:extendee -> google.protobuf.MethodOptions
	3, // 1: options.actor_base:extendee -> google.protobuf.FileOptions
	4, // 2: options.actor:extendee -> google.protobuf.ServiceOptions
	0, // 3: options.method_options:type_name -> options.MethodOptions
	1, // 4: options.actor_base:type_name -> options.ActorBase
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	3, // [3:5] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_options_options_proto_init() }
func file_options_options_proto_init() {
	if File_options_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_options_options_proto_rawDesc), len(file_options_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_options_options_proto_goTypes,
		DependencyIndexes: file_options_options_proto_depIdxs,
		MessageInfos:      file_options_options_proto_msgTypes,
		ExtensionInfos:    file_options_options_proto_extTypes,
	}.Build()
	File_options_options_proto = out.File
	file_options_options_proto_goTypes = nil
	file_options_options_proto_depIdxs = nil
}
