// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: actor_router.proto

package tcaplus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActorRouter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Identity      string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	Member        string                 `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	ActorID       string                 `protobuf:"bytes,5,opt,name=actorID,proto3" json:"actorID,omitempty"`
	LockTime      uint64                 `protobuf:"varint,6,opt,name=lockTime,proto3" json:"lockTime,omitempty"`
	ActiveTime    uint64                 `protobuf:"varint,7,opt,name=activeTime,proto3" json:"activeTime,omitempty"`
	TerminateTime uint64                 `protobuf:"varint,8,opt,name=terminateTime,proto3" json:"terminateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorRouter) Reset() {
	*x = ActorRouter{}
	mi := &file_actor_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorRouter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorRouter) ProtoMessage() {}

func (x *ActorRouter) ProtoReflect() protoreflect.Message {
	mi := &file_actor_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorRouter.ProtoReflect.Descriptor instead.
func (*ActorRouter) Descriptor() ([]byte, []int) {
	return file_actor_router_proto_rawDescGZIP(), []int{0}
}

func (x *ActorRouter) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ActorRouter) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *ActorRouter) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *ActorRouter) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ActorRouter) GetActorID() string {
	if x != nil {
		return x.ActorID
	}
	return ""
}

func (x *ActorRouter) GetLockTime() uint64 {
	if x != nil {
		return x.LockTime
	}
	return 0
}

func (x *ActorRouter) GetActiveTime() uint64 {
	if x != nil {
		return x.ActiveTime
	}
	return 0
}

func (x *ActorRouter) GetTerminateTime() uint64 {
	if x != nil {
		return x.TerminateTime
	}
	return 0
}

var File_actor_router_proto protoreflect.FileDescriptor

const file_actor_router_proto_rawDesc = "" +
	"\n" +
	"\x12actor_router.proto\x12\x0etcaplusservice\x1a google/protobuf/descriptor.proto\x1a\x1dtcaplusservice.optionv1.proto\"\xfe\x01\n" +
	"\vActorRouter\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12\x16\n" +
	"\x06member\x18\x03 \x01(\tR\x06member\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x18\n" +
	"\aactorID\x18\x05 \x01(\tR\aactorID\x12\x1a\n" +
	"\blockTime\x18\x06 \x01(\x04R\blockTime\x12\x1e\n" +
	"\n" +
	"activeTime\x18\a \x01(\x04R\n" +
	"activeTime\x12$\n" +
	"\rterminateTime\x18\b \x01(\x04R\rterminateTime:\x11\x82\xa6\x1d\rkind,identityB\x11Z\x0fdbproto/tcaplusb\x06proto3"

var (
	file_actor_router_proto_rawDescOnce sync.Once
	file_actor_router_proto_rawDescData []byte
)

func file_actor_router_proto_rawDescGZIP() []byte {
	file_actor_router_proto_rawDescOnce.Do(func() {
		file_actor_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_actor_router_proto_rawDesc), len(file_actor_router_proto_rawDesc)))
	})
	return file_actor_router_proto_rawDescData
}

var file_actor_router_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_actor_router_proto_goTypes = []any{
	(*ActorRouter)(nil), // 0: tcaplusservice.ActorRouter
}
var file_actor_router_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_actor_router_proto_init() }
func file_actor_router_proto_init() {
	if File_actor_router_proto != nil {
		return
	}
	file_tcaplusservice_optionv1_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_actor_router_proto_rawDesc), len(file_actor_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_actor_router_proto_goTypes,
		DependencyIndexes: file_actor_router_proto_depIdxs,
		MessageInfos:      file_actor_router_proto_msgTypes,
	}.Build()
	File_actor_router_proto = out.File
	file_actor_router_proto_goTypes = nil
	file_actor_router_proto_depIdxs = nil
}
