// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: service/example/grain-oneway/proto/actor_base.proto

package proto

import (
	_ "gitee.com/wxdqing/protoc-gen-go-grain/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_example_grain_oneway_proto_actor_base_proto protoreflect.FileDescriptor

const file_service_example_grain_oneway_proto_actor_base_proto_rawDesc = "" +
	"\n" +
	"3service/example/grain-oneway/proto/actor_base.proto\x12\vgrainoneway\x1a\x15options/options.protoBX\x82\xb5\x18\x0e\n" +
	"\x06player\x1a\x04gameZDgithub.com/asynkron/protoactor-go/service/example/grain-oneway/protob\x06proto3"

var file_service_example_grain_oneway_proto_actor_base_proto_goTypes = []any{}
var file_service_example_grain_oneway_proto_actor_base_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_example_grain_oneway_proto_actor_base_proto_init() }
func file_service_example_grain_oneway_proto_actor_base_proto_init() {
	if File_service_example_grain_oneway_proto_actor_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_example_grain_oneway_proto_actor_base_proto_rawDesc), len(file_service_example_grain_oneway_proto_actor_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_example_grain_oneway_proto_actor_base_proto_goTypes,
		DependencyIndexes: file_service_example_grain_oneway_proto_actor_base_proto_depIdxs,
	}.Build()
	File_service_example_grain_oneway_proto_actor_base_proto = out.File
	file_service_example_grain_oneway_proto_actor_base_proto_goTypes = nil
	file_service_example_grain_oneway_proto_actor_base_proto_depIdxs = nil
}
