// Code generated by protoc-gen-grain. DO NOT EDIT.
// versions:
//  protoc-gen-grain v0.7.0
//  protoc           v7.34.1
// source: service/example/grain-oneway/proto/grain_oneway.proto

package proto

import (
	fmt "fmt"
	cluster "github.com/asynkron/protoactor-go/service/cluster"
	proto "google.golang.org/protobuf/proto"
	slog "log/slog"
)

const GrainKindNamePlayer = "player"
const GrainNodeTypePlayer = "game"
const GrainModuleNamePlayer = "player"

// GetPlayerGrainClient instantiates a new PlayerGrainClient with the given identity.
func GetPlayerGrainClient(c *cluster.Cluster, id string) *PlayerGrainClient {
	if c == nil {
		panic(fmt.Errorf("nil cluster instance"))
	}
	if id == "" {
		panic(fmt.Errorf("empty id"))
	}
	return &PlayerGrainClient{Identity: id, cluster: c}
}

// PlayerGrainClient holds the base data for the Player grain.
type PlayerGrainClient struct {
	Identity string
	cluster  *cluster.Cluster
}

// BasePlayerGrainClient provides shared cluster access and default call options.
type BasePlayerGrainClient struct {
	ClusterFn func() *cluster.Cluster
	Opts      []cluster.GrainCallOption
}

// NewBasePlayerGrainClient creates a base client with default call options.
func NewBasePlayerGrainClient(c func() *cluster.Cluster, opts ...cluster.GrainCallOption) *BasePlayerGrainClient {
	return &BasePlayerGrainClient{ClusterFn: c, Opts: opts}
}

func normalizePlayerPlacementContext(placementContext *cluster.PlacementContext) (*cluster.PlacementContext, error) {
	if placementContext == nil {
		return &cluster.PlacementContext{NodeType: GrainNodeTypePlayer}, nil
	}
	if placementContext.NodeType != "" && placementContext.NodeType != GrainNodeTypePlayer {
		return nil, fmt.Errorf("placement node type %q does not match kind %q node type %q", placementContext.NodeType, GrainKindNamePlayer, GrainNodeTypePlayer)
	}
	cloned := *placementContext
	cloned.NodeType = GrainNodeTypePlayer
	return &cloned, nil
}

// PingSend delivers a one-way grain message.
func (h *BasePlayerGrainClient) PingSend(identity string, placementContext *cluster.PlacementContext, r *PingRequest, opts ...cluster.GrainCallOption) error {
	return GetPlayerGrainClient(h.ClusterFn(), identity).PingSend(placementContext, r, h.mergeOpts(opts)...)
}

func (h *BasePlayerGrainClient) mergeOpts(opts []cluster.GrainCallOption) []cluster.GrainCallOption {
	if len(h.Opts) == 0 {
		return opts
	}
	merged := make([]cluster.GrainCallOption, 0, len(h.Opts)+len(opts))
	merged = append(merged, h.Opts...)
	return append(merged, opts...)
}

// PingSend delivers a one-way grain message.
func (g *PlayerGrainClient) PingSend(placementContext *cluster.PlacementContext, r *PingRequest, opts ...cluster.GrainCallOption) error {
	var err error
	placementContext, err = normalizePlayerPlacementContext(placementContext)
	if err != nil {
		return err
	}
	if g.cluster.Config.RequestLog {
		g.cluster.Logger().Info("Sending", slog.String("identity", g.Identity), slog.String("kind", "player"), slog.String("method", "Ping"), slog.Any("request", r))
	}
	data, err := proto.Marshal(r)
	if err != nil {
		return err
	}
	req := &cluster.GrainRequest{MethodIndex: 0, MessageData: data, OneWay: true}
	return g.cluster.Send(placementContext, g.Identity, GrainKindNamePlayer, req, opts...)
}
