// Code generated by protoc-gen-grain. DO NOT EDIT.
// versions:
//  protoc-gen-grain v0.7.0
//  protoc           v7.34.1
// source: service/example/grain-oneway/proto/grain_oneway.proto

package proto

import (
	context "context"
	fmt "fmt"
	actor "github.com/asynkron/protoactor-go/actor"
	cluster "github.com/asynkron/protoactor-go/service/cluster"
	grainactor "github.com/asynkron/protoactor-go/service/grainactor"
	proto "google.golang.org/protobuf/proto"
	slog "log/slog"
)

const ActorKindNamePlayer = "player_equip"
const ActorNodeTypePlayer = "game"
const ActorGroupNamePlayer = "player"

var xPlayerFactory func() Player

// PlayerFactory produces a Player
func PlayerFactory(factory func() Player) {
	xPlayerFactory = factory
}

// GetPlayerGrainClient instantiates a new PlayerGrainClient with given Identity
func GetPlayerGrainClient(c *cluster.Cluster, id string) *PlayerGrainClient {
	if c == nil {
		panic(fmt.Errorf("nil cluster instance"))
	}
	if id == "" {
		panic(fmt.Errorf("empty id"))
	}
	return &PlayerGrainClient{Identity: id, cluster: c}
}

// GetPlayerKind instantiates a new cluster.Kind for Player

// GetPlayerKind instantiates a new cluster.Kind for Player

// Player interfaces the services available to the Player
type Player interface {
	Ping(ctx context.Context, req *PingRequest) error
}

// PlayerGrainClient holds the base data for the PlayerGrain
type PlayerGrainClient struct {
	Identity string
	cluster  *cluster.Cluster
}

// BasePlayerGrainClient provides shared cluster access and default call options for Player grains.
type BasePlayerGrainClient struct {
	ClusterFn func() *cluster.Cluster
	Opts      []cluster.GrainCallOption
}

// NewBasePlayerGrainClient creates a BasePlayerGrainClient with default call options.
func NewBasePlayerGrainClient(c func() *cluster.Cluster, opts ...cluster.GrainCallOption) *BasePlayerGrainClient {
	return &BasePlayerGrainClient{ClusterFn: c, Opts: opts}
}

// PingSend delivers a one-way grain message without waiting for a response.
func (h *BasePlayerGrainClient) PingSend(identity string, r *PingRequest, opts ...cluster.GrainCallOption) error {
	cli := GetPlayerGrainClient(h.ClusterFn(), identity)
	return cli.PingSend(identity, r, h.mergeOpts(opts)...)
}

func (h *BasePlayerGrainClient) mergeOpts(opts []cluster.GrainCallOption) []cluster.GrainCallOption {
	if len(h.Opts) == 0 {
		return opts
	}
	merged := make([]cluster.GrainCallOption, 0, len(h.Opts)+len(opts))
	merged = append(merged, h.Opts...)
	merged = append(merged, opts...)
	return merged
}

// PingSend delivers a one-way grain message without waiting for a response.
func (g *PlayerGrainClient) PingSend(identity string, r *PingRequest, opts ...cluster.GrainCallOption) error {
	routeKey, err := routeKeyFromServerIDOptions(opts)
	if err != nil {
		return err
	}
	return g.PingSendByRouteKey(identity, routeKey, r, opts...)
}
func (g *PlayerGrainClient) PingSendByRouteKey(identity string, routeKey uint64, r *PingRequest, opts ...cluster.GrainCallOption) error {
	placementContext := &cluster.PlacementContext{NodeType: "game", RouteKey: routeKey}
	return g.PingSendWithPlacementAndRouteKey(placementContext, routeKey, identity, r, opts...)
}

func (g *PlayerGrainClient) PingSendWithPlacement(placementContext *cluster.PlacementContext, identity string, r *PingRequest, opts ...cluster.GrainCallOption) error {
	return g.PingSendWithPlacementAndRouteKey(placementContext, 0, identity, r, opts...)
}

func (g *PlayerGrainClient) PingSendWithPlacementAndRouteKey(placementContext *cluster.PlacementContext, routeKey uint64, identity string, r *PingRequest, opts ...cluster.GrainCallOption) error {
	if g.cluster.Config.RequestLog {
		g.cluster.Logger().Info("Sending", slog.String("identity", g.Identity), slog.String("kind", "Player"), slog.String("method", "Ping"), slog.Any("request", r))
	}
	bytes, err := proto.Marshal(r)
	if err != nil {
		return err
	}
	reqMsg := &cluster.GrainRequest{MethodIndex: 0, MessageData: bytes, OneWay: true, RouteKey: routeKey, HasRouteKey: true}
	return g.cluster.Send(placementContext, identity, ActorKindNamePlayer, reqMsg, opts...)
}

type PlayerActor interface {
	Player
}

type playerHandler struct {
	handler PlayerActor
}

type playerServerIDKey struct{}

// WithServerIDKey routes player actor calls by server_id.
func WithServerIDKey(serverID uint64) cluster.GrainCallOption {
	return cluster.WithRouteKey(serverID)
}

// GetServerIDKey returns the server_id route key from ctx.
func GetServerIDKey(ctx context.Context) (uint64, error) {
	serverID, ok := ctx.Value(playerServerIDKey{}).(uint64)
	if !ok {
		return 0, fmt.Errorf("missing route key server_id")
	}

	return serverID, nil
}

func routeKeyFromServerIDOptions(opts []cluster.GrainCallOption) (uint64, error) {
	config := &cluster.GrainCallConfig{}
	for _, opt := range opts {
		opt(config)
	}
	if !config.HasRouteKey {
		return 0, fmt.Errorf("missing route key option WithServerIDKey")
	}

	return config.RouteKey, nil
}

func (h *playerHandler) Receive(ctx grainactor.Context, req *cluster.GrainRequest) (proto.Message, error) {
	switch req.MethodIndex {
	case 0:
		msg := &PingRequest{}
		if err := proto.Unmarshal(req.MessageData, msg); err != nil {
			return nil, cluster.NewGrainErrorResponse(cluster.ErrorReason_INVALID_ARGUMENT, err.Error()).
				WithMetadata(map[string]string{
					"argument": msg.String(),
				})
		}
		if !req.HasRouteKey {
			return nil, fmt.Errorf("missing route key server_id")
		}
		handlerCtx := grainactor.ToContext(ctx, grainactor.WithValue(playerServerIDKey{}, req.RouteKey))
		if err := h.handler.Ping(handlerCtx, msg); err != nil {
			return nil, err
		}
		return nil, nil
	default:
		return nil, cluster.NewGrainErrorResponse(cluster.ErrorReason_NOT_FOUND, fmt.Sprintf("unknown grain method index %d", req.MethodIndex))
	}
}

func NewPlayerBaseActor(handler PlayerActor, state any, opts ...grainactor.Option) actor.Actor {
	if state != nil {
		opts = append(opts, grainactor.WithState(state))
	}
	return grainactor.NewBaseActor("player", "player_equip", &playerHandler{handler: handler}, opts...)
}

func NewPlayerKind(handler PlayerActor, state any, opts ...actor.PropsOption) *cluster.Kind {
	props := actor.PropsFromProducer(func() actor.Actor {
		return NewPlayerBaseActor(handler, state)
	}, opts...)
	return cluster.NewKind("player_equip", props)
}

func respond[T proto.Message](ctx cluster.GrainContext) func(T) {
	return func(resp T) {
		ctx.Respond(resp)
	}
}
