// Code generated by protoc-gen-grain. DO NOT EDIT.

package proto

import (
	cluster "github.com/asynkron/protoactor-go/service/cluster"
)

var (
	allServiceGrainClients = &allServiceGrainClientSet{}
)

type allServiceGrainClientSet struct {
	basePlayerGrainClient *BasePlayerGrainClient
}

// InitServiceGrainClients initializes shared base grain clients for all generated grain services.
func InitServiceGrainClients(fn func() *cluster.Cluster, opts ...cluster.GrainCallOption) {
	allServiceGrainClients.basePlayerGrainClient = NewBasePlayerGrainClient(fn, opts...)
}

// GetBasePlayerGrainClient returns the shared base client for Player.
func GetBasePlayerGrainClient() *BasePlayerGrainClient {
	return allServiceGrainClients.basePlayerGrainClient
}
