// Code generated by protoc-gen-grain. DO NOT EDIT.
// versions:
//  protoc-gen-grain v0.7.0
//  protoc           v7.34.1
// source: service/example/grain-oneway/proto/grain_oneway.proto

package proto

import (
	context "context"
	fmt "fmt"
	actor "github.com/asynkron/protoactor-go/actor"
	cluster "github.com/asynkron/protoactor-go/service/cluster"
	grainactor "github.com/asynkron/protoactor-go/service/grainactor"
	proto "google.golang.org/protobuf/proto"
)

var xPlayerFactory func() Player

// PlayerFactory produces a Player
func PlayerFactory(factory func() Player) {
	xPlayerFactory = factory
}

// Player interfaces the services available to the Player
type Player interface {
	Ping(ctx context.Context, req *PingRequest) error
}

type PlayerActor interface {
	Player
}

type playerHandler struct {
	handler PlayerActor
}

func (h *playerHandler) Receive(ctx grainactor.Context, req *cluster.GrainRequest) (proto.Message, error) {
	switch req.MethodIndex {
	case 0:
		msg := &PingRequest{}
		if err := proto.Unmarshal(req.MessageData, msg); err != nil {
			return nil, cluster.NewGrainErrorResponse(cluster.ErrorReason_INVALID_ARGUMENT, err.Error()).
				WithMetadata(map[string]string{
					"argument": msg.String(),
				})
		}
		handlerCtx := grainactor.ToContext(ctx, grainactor.WithModule("player"))
		if err := h.handler.Ping(handlerCtx, msg); err != nil {
			return nil, err
		}
		return nil, nil
	default:
		return nil, cluster.NewGrainErrorResponse(cluster.ErrorReason_NOT_FOUND, fmt.Sprintf("unknown grain method index %d for kind player", req.MethodIndex))
	}
}

func NewPlayerBaseActor(handler PlayerActor, state any, opts ...grainactor.Option) actor.Actor {
	if state != nil {
		opts = append(opts, grainactor.WithState(state))
	}
	return grainactor.NewBaseActor("player", &playerHandler{handler: handler}, opts...)
}

func NewPlayerKind(handler PlayerActor, state any, opts ...actor.PropsOption) *cluster.Kind {
	props := actor.PropsFromProducer(func() actor.Actor {
		return NewPlayerBaseActor(handler, state)
	}, opts...)
	return cluster.NewKind("player", props)
}

func respond[T proto.Message](ctx cluster.GrainContext) func(T) {
	return func(resp T) {
		ctx.Respond(resp)
	}
}
