// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: service/example/grain-oneway/proto/grain_oneway.proto

package proto

import (
	_ "gitee.com/wxdqing/protoc-gen-go-grain/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      uint64                 `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_service_example_grain_oneway_proto_grain_oneway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_example_grain_oneway_proto_grain_oneway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_service_example_grain_oneway_proto_grain_oneway_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetServerId() uint64 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_service_example_grain_oneway_proto_grain_oneway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_example_grain_oneway_proto_grain_oneway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_service_example_grain_oneway_proto_grain_oneway_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

var File_service_example_grain_oneway_proto_grain_oneway_proto protoreflect.FileDescriptor

const file_service_example_grain_oneway_proto_grain_oneway_proto_rawDesc = "" +
	"\n" +
	"5service/example/grain-oneway/proto/grain_oneway.proto\x12\vgrainoneway\x1a\x15options/options.proto\"*\n" +
	"\vPingRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x04R\bserverId\"/\n" +
	"\fPingResponse\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime2c\n" +
	"\x06Player\x12C\n" +
	"\x04Ping\x12\x18.grainoneway.PingRequest\x1a\x19.grainoneway.PingResponse\"\x06\x82\xb5\x18\x02\x18\x01\x1a\x14\x82\xb5\x18\x06player\x8a\xb5\x18\x06playerBFZDgithub.com/asynkron/protoactor-go/service/example/grain-oneway/protob\x06proto3"

var (
	file_service_example_grain_oneway_proto_grain_oneway_proto_rawDescOnce sync.Once
	file_service_example_grain_oneway_proto_grain_oneway_proto_rawDescData []byte
)

func file_service_example_grain_oneway_proto_grain_oneway_proto_rawDescGZIP() []byte {
	file_service_example_grain_oneway_proto_grain_oneway_proto_rawDescOnce.Do(func() {
		file_service_example_grain_oneway_proto_grain_oneway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_example_grain_oneway_proto_grain_oneway_proto_rawDesc), len(file_service_example_grain_oneway_proto_grain_oneway_proto_rawDesc)))
	})
	return file_service_example_grain_oneway_proto_grain_oneway_proto_rawDescData
}

var file_service_example_grain_oneway_proto_grain_oneway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_example_grain_oneway_proto_grain_oneway_proto_goTypes = []any{
	(*PingRequest)(nil),  // 0: grainoneway.PingRequest
	(*PingResponse)(nil), // 1: grainoneway.PingResponse
}
var file_service_example_grain_oneway_proto_grain_oneway_proto_depIdxs = []int32{
	0, // 0: grainoneway.Player.Ping:input_type -> grainoneway.PingRequest
	1, // 1: grainoneway.Player.Ping:output_type -> grainoneway.PingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_example_grain_oneway_proto_grain_oneway_proto_init() }
func file_service_example_grain_oneway_proto_grain_oneway_proto_init() {
	if File_service_example_grain_oneway_proto_grain_oneway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_example_grain_oneway_proto_grain_oneway_proto_rawDesc), len(file_service_example_grain_oneway_proto_grain_oneway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_example_grain_oneway_proto_grain_oneway_proto_goTypes,
		DependencyIndexes: file_service_example_grain_oneway_proto_grain_oneway_proto_depIdxs,
		MessageInfos:      file_service_example_grain_oneway_proto_grain_oneway_proto_msgTypes,
	}.Build()
	File_service_example_grain_oneway_proto_grain_oneway_proto = out.File
	file_service_example_grain_oneway_proto_grain_oneway_proto_goTypes = nil
	file_service_example_grain_oneway_proto_grain_oneway_proto_depIdxs = nil
}
